### ISSUE TITLE
GameObject.AddComponent API change

### ISSUE THREAD

**Issue by qwarnant** [alexandreweiler/ALPS-VR#2]
Hello,

I've noticed that the GameObject.AddComponent method has been updated in Unity 5.0. The new API provides the AddComponent method which requires a System.Type parameter, not a string anymore. 

> error CS1502 : The best overloaded method match for "UnityEngine.GameObject.AddComponent(System.Type)" has some invalid arguments.
> error CS1502 : Argument "#1" cannot convert "string" expression to type "System.Type".

In ALPSController.cs and ALPSControllerLight.cs classes, in the Android specific sections, you have to replace this line :
```cs
head.AddComponent("ALPSGyro");
```` 
with the following one to remove the compiler errors :
```cs
System.Type GyroType = typeof(ALPSGyro);
head.AddComponent(GyroType);
```

Regards

**Comment by alexandreweiler** [comment]
Salut Quentin,

merci pour ta contribution et désolé pour le retard. Je viens de merge tes
modifications.

Alexandre

2015-03-11 21:53 GMT+01:00 Quentin Warnant <notifications@github.com>:

**Comment by qwarnant** [comment]
Pas de soucis, c'est avec plaisir ! En revanche, j'ai oublié de passer l'entièreté des sources plugin sous l'ApiUpdateRunner script de Unity 5.0, qui remplace certains éléments obsolètes, tu devrais donc le faire.

Cordialement
